variable "zone" { default = "us-west-1-a" }
variable "url" { default = "https://kith.com/collections/kith/products/kh9588-101"}
variable "size" { default = "L"}
variable "email" { default = "johnsmith@gmail.com"}
variable "firstName" { default = "John"}
variable "lastName" { default = "Smith"}
variable "address" { default = "8888 Kith Avenue"}
variable "city" {default = "Night City"}
variable "zip" { default = "88888"}
variable "phone" { default = "5556667777"}
variable "cardNum" { default = "4444 5555 6666 7777"}
variable "cardName"  { default = "John Smith"}
variable "cardExp" { default = "07 21"}
variable "ccv" { default = "456"}
